version: '3.9'

services:
  web:
    container_name: nebt-web
    build: ./docker/web
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html

  db: 
    container_name: nebt-db
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: nebt
      MYSQL_DATABASE: nebt-db
      MYSQL_USER: nebt
      MYSQL_PASSWORD: nebt
    volumes:
      - ./db-mysql:/var/lib/mysql

  adminer:
    container_name: nebt-adminer
    image: adminer
    ports:
      - 8080:8080